### ISSUE TITLE
Treat mypy.ini and .mypy.ini the same

### ISSUE THREAD

**Issue by Richardk2n** [Richardk2n/mypy-ls#6]
Currently all parent directories up to root are searched for a `mypy.ini` before the search for a `.mypy.ini` is started. If @asford does not disagree, i would switch it to searching for both at the same time.

**Comment by asford** [comment]
+1 from me, this makes a lot of sense. I'm not %100 sure how this maps to mypy's config file discovery, which is outlined:

https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file

I *think* the search should be `mypy.ini` or `.mypy.ini` in each directory, walking up toward the root.
Do you think this should be expanded to include `pyproject.toml` and `setup.cfg` as per the `mypy` behavior?

**Comment by Richardk2n** [comment]
I cannot (easily) (and do not want to) mimic the mypy behavior exactly. There are arguments to include these files, but it would (depending on implementation) break my usecase for config discovery as it is now. So I won't add them for now, but if someone presents a usecase requiring them to be included, I will change that.

**Comment by zsiciarz** [comment]
+1 for supporting `pyproject.toml`. For what is worth, it's the best way we have at the moment to minimize the clutter of config files in project root. Since I moved mypy config from `mypy.ini` to `pyproject.toml`, I now need to add another config file for mypy-pylsp. So the net number of configuration files didn't really change.

```
{
    "enabled": True,
    "overrides": ["--config-file", "/home/zbigniew/Development/myproject/pyproject.toml", True]
}

```
